version: '3.8'
name: jogayjoga

services:

  db-jogayjoga:
    container_name: jogayjoga-db-jogayjoga
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jogayjoga
      - POSTGRES_PASSWORD=jogayjoga
      - POSTGRES_DB=jogayjoga
    volumes:
      - $VOLUME/postgres/jogayjoga/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    networks:
      - private-network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - private-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - private-network

  prometheus:
    image: prom/prometheus:latest
    container_name: jogayjoga-prometheus
    ports:
      - 9090:9090
    volumes:
      - $VOLUME/prometheus:/etc/prometheus
      - $VOLUME/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - private-network

  grafana:
    container_name: jogayjoga-grafana
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - $VOLUME/grafana:/var/lib/grafana
      - $VOLUME/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    restart: always
    networks:
      - private-network

  discovery:
    build:
      context: ../jogayjoga.discovery/
      dockerfile: Dockerfile
    container_name: jogayjoga-discovery
    image: jogayjoga-discovery:latest
    ports:
      - 8761:8761
    restart: always
    networks:
      - private-network

  gateway:
    build:
      context: ../jogayjoga.gateway/
      dockerfile: Dockerfile
    container_name: jogayjoga-gateway
    image: jogayjoga-gateway:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka/
    networks:
      - private-network
    depends_on:
      - discovery

  account:
    build: 
      context: ../jogayjoga.account-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-account
    image: jogayjoga-account:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
  

  auth:
    build:
      context: ../jogayjoga.auth-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-auth
    image: jogayjoga-auth:latest
    environment:
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private-network
    depends_on:
      - discovery
      - account
    
  
  sport:
    build: 
      context: ../jogayjoga.sport-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-sport
    image: jogayjoga-sport:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account
      - redis

  court:
    build: 
      context: ../jogayjoga.court-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-court
    image: jogayjoga-court:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account
      - redis
      - kafka  # Add kafka as dependency

  group:
    build: 
      context: ../jogayjoga.group-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-group
    image: jogayjoga-group:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account
      - redis
      - kafka  # Add kafka as dependency
      
networks:
  private-network:
    driver: bridge
