version: '3.8'
name: jogayjoga

services:

  db-jogayjoga:
    container_name: jogayjoga-db-jogayjoga
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jogayjoga
      - POSTGRES_PASSWORD=jogayjoga
      - POSTGRES_DB=jogayjoga
    volumes:
      - $VOLUME/postgres/jogayjoga/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: jogayjoga-prometheus
    ports:
      - 9090:9090
    volumes:
      - $VOLUME/prometheus:/etc/prometheus
      - $VOLUME/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - private-network

  grafana:
    container_name: jogayjoga-grafana
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - $VOLUME/grafana:/var/lib/grafana
      - $VOLUME/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources      
    restart: always
    networks:
      - private-network

  discovery:
    build:
      context: ../jogayjoga.discovery/
      dockerfile: Dockerfile
    container_name: jogayjoga-discovery
    image: jogayjoga-discovery:latest
    ports:
      - 8761:8761
    restart: always
    networks:
      - private-network

  gateway:
    build:
      context: ../jogayjoga.gateway/
      dockerfile: Dockerfile
    container_name: jogayjoga-gateway
    image: jogayjoga-gateway:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka/
    networks:
      - private-network
    depends_on:
      - discovery

  account:
    build: 
      context: ../jogayjoga.account-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-account
    image: jogayjoga-account:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
  

  auth:
    build:
      context: ../jogayjoga.auth-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-auth
    image: jogayjoga-auth:latest
    environment:
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka/
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - private-network
    depends_on:
      - discovery
      - account
    
  
  sport:
    build: 
      context: ../jogayjoga.sport-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-sport
    image: jogayjoga-sport:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account


  court:
    build: 
      context: ../jogayjoga.court-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-court
    image: jogayjoga-court:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account

  group:
    build: 
      context: ../jogayjoga.group-resource/
      dockerfile: Dockerfile
    container_name: jogayjoga-group
    image: jogayjoga-group:latest
    environment:
      - spring.datasource.url=jdbc:postgresql://jogayjoga-db-jogayjoga:5432/jogayjoga
      - spring.datasource.username=jogayjoga
      - spring.datasource.password=jogayjoga
      - eureka.client.service-url.defaultZone=http://jogayjoga-discovery:8761/eureka

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-jogayjoga
      - discovery
      - auth
      - account
      

  jenkins:
    container_name: jenkins
    build:
    dockerfile_inline: |
        FROM jenkins/jenkins:jdk21
        USER root
        RUN apt-get update && apt-get install -y lsb-release
        RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
        https://download.docker.com/linux/debian/gpg
        RUN echo "deb [arch=$(dpkg --print-architecture) \
        signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
        https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
        RUN apt-get update && apt-get install -y docker-ce maven

        RUN apt-get install -y apt-transport-https ca-certificates curl
        RUN curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        RUN chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        RUN chmod 644 /etc/apt/sources.list.d/kubernetes.list
        RUN apt-get update
        RUN apt-get install -y kubectl

        RUN usermod -aG docker jenkins
    ports:
        - 9080:8080
        - 50000:50000 
    volumes:
        - $CONFIG/jenkins:/var/jenkins_home
    restart: always
    networks:
        - infra

networks:
  private-network:
    driver: bridge